site_name: Cross-Modal Neural Encoding
site_author: Helena Balabin

nav:
  - Home: index.md
  - Scientific Context: 01_scientific_context.md
  - Datasets: 02_datasets.md
  - Feature Extraction: 03_feature_extraction.md
  - Neural Encoding: 04_neural_encoding.md
  - Structural Analysis: 05_structural_analysis.md
  - Residual Neural Encoding: 06_residual_encoding.md
  - Models: 07_models.md
  - Evaluation & Statistics: 08_evaluation_and_statistics.md
  - Configuration: 09_configuration.md
  - Visualization: 10_visualization.md
  - Predict Modalities: 11_predict_modalities.md
