site_name: Cross-Modal Neural Encoding
site_author: Helena Balabin

nav:
  - Home: index.md
  - Scientific Context: 01_scientific_context.md
  - Datasets: 02_datasets.md
  - Feature Extraction: 03_feature_extraction.md
  - Neural Encoding: 04_neural_encoding.md
  - Evaluation & Statistics: 05_evaluation_and_statistics.md
  - Visualization: 06_visualization.md
  - Configuration: 07_configuration.md
