site_name: Cross-Modal Neural Encoding
site_author: Helena Balabin

nav:
  - Home: index.md
  - Scientific Context: 01_scientific_context.md
  - Datasets: 02_datasets.md
  - Feature Extraction: 03_feature_extraction.md
  - Neural Encoding: 04_neural_encoding.md
  - Residual Neural Encoding: 05_residual_encoding.md
  - Models: 06_models.md
  - Evaluation & Statistics: 07_evaluation_and_statistics.md
  - Configuration: 08_configuration.md
  - Visualization: 09_visualization.md
  - Predict Modalities: 10_predict_modalities.md
